#ifndef DISCORDPP_EVENTS_H
#define DISCORDPP_EVENTS_H

namespace discord {
	const inline std::unordered_map<std::string, int> event_m{
		{ "READY", 0 },
		{ "RESUMED", 1 },
		{ "RECONNECT", 2},
		{ "INVALID_SESSION", 3 },
		{ "CHANNEL_CREATE", 4 },
		{ "CHANNEL_UPDATE", 5 },
		{ "CHANNEL_DELETE", 6 },
		{ "CHANNEL_PINS_UPDATE", 7 },
		{ "GUILD_CREATE", 8 },
		{ "GUILD_UPDATE", 9 },
		{ "GUILD_DELETE", 10 },
		{ "GUILD_BAN_ADD", 11 },
		{ "GUILD_BAN_REMOVE", 12 },
		{ "GUILD_EMOJIS_UPDATE", 13 },
		{ "GUILD_INTEGRATIONS_UPDATE", 14 },
		{ "GUILD_MEMBER_ADD", 15 },
		{ "GUILD_MEMBER_REMOVE", 16 },
		{ "GUILD_MEMBER_UPDATE", 17 },
		{ "GUILD_MEMBERS_CHUNK", 18 },
		{ "GUILD_ROLE_CREATE", 19 },
		{ "GUILD_ROLE_UPDATE", 20 },
		{ "GUILD_ROLE_DELETE", 21 },
		{ "MESSAGE_CREATE", 22 },
		{ "MESSAGE_UPDATE", 23 },
		{ "MESSAGE_DELETE", 24 },
		{ "MESSAGE_DELETE_BULK", 25 },
		{ "MESSAGE_REACTION_ADD", 26 },
		{ "MESSAGE_REACTION_REMOVE", 27 },
		{ "MESSAGE_REACTION_REMOVE_ALL", 28 },
		{ "PRESENCE_UPDATE", 29 },
		{ "TYPING_START", 30 },
		{ "USER_UPDATE", 31 },
		{ "VOICE_STATE_UPDATE", 32 },
		{ "VOICE_SERVER_UPDATE", 33 },
		{ "WEBHOOKS_UPDATE", 34 }
	};

	enum events : int {
		ready = 0,
		resumed = 1,
		reconnect = 2,
		invalid_session = 3,
		channel_create = 4,
		channel_update = 5,
		channel_delete = 6,
		channel_pins_update = 7,
		guild_create = 8,
		guild_update = 9,
		guild_delete = 10,
		guild_ban_add = 11,
		guild_ban_remove = 12,
		guild_emojis_update = 13,
		guild_integrations_update = 14,
		guild_member_add = 15,
		guild_member_remove = 16,
		guild_member_update = 17,
		guild_members_chunk = 18,
		guild_role_create = 19,
		guild_role_update = 20,
		guild_role_delete = 21,
		message_create = 22,
		message_update = 23,
		message_delete = 24,
		message_delete_bulk = 25,
		message_reaction_add = 26,
		message_reaction_remove = 27,
		message_reaction_remove_all = 28,
		presence_update = 29,
		typing_start = 30,
		user_update = 31,
		voice_state_update = 32,
		voice_server_update = 33,
		webhooks_update = 34
	};
}

#endif